spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: kamran
      password: mypassmypass
      authentication-database: admin

  application:
    name: Post-Service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8085

