spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reporting-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true # Important for manual offset management
  cassandra:
    keyspace-name: reports
    contact-points: localhost
    port: 9042
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 8088

